version: 0.2

phases:
  install:
    runtime_versions:
      nodejs: 10
    pre_build:
      commands:
        - npm install
        - aws s3 rm --recursive "s3://${hall-thruster-database}/" 
    build:
      commands:
        - npm run build
    post_build:
      commands:
        - aws s3 sync ./dist s3://hall-thruster-database
artifacts:
  files:
    - '**/*'
  base-directory: dist